Repository Gradient-and-Co/sigma-school, pull requests merged in 2025-04, with the labels that each got.

#19 backend core domain logic
  internal/core/domain/payment.go
  internal/core/errs/errors.go
  internal/core/port/auth.go
  internal/core/port/course.go
  internal/core/port/lesson.go
  internal/core/port/payment.go
  internal/core/port/repository.go
  internal/core/port/review.go
  internal/core/port/school.go
  internal/core/port/service.go
  internal/core/port/stat.go
  internal/core/port/storage.go
  internal/core/port/user.go
  internal/core/service/auth.go
  internal/core/service/course.go
  internal/core/service/lesson.go
  internal/core/service/media.go
  internal/core/service/mocks/auth.go
  internal/core/service/mocks/course.go
  internal/core/service/mocks/lesson.go
  internal/core/service/mocks/payment.go
  internal/core/service/mocks/review.go
  internal/core/service/mocks/school.go
  internal/core/service/mocks/stat.go
  internal/core/service/mocks/storage.go
  internal/core/service/mocks/user.go
  internal/core/service/payment.go
  internal/core/service/review.go
  internal/core/service/school.go
  internal/core/service/stat.go
  internal/core/service/test/unit/auth_test.go
  internal/core/service/test/unit/course.go
  internal/core/service/test/unit/course_test.go
  internal/core/service/test/unit/file.go
  internal/core/service/test/unit/lesson.go
  internal/core/service/test/unit/lesson_test.go
  internal/core/service/test/unit/media_test.go
  internal/core/service/test/unit/payment_test.go
  internal/core/service/test/unit/review.go
  internal/core/service/test/unit/review_test.go
  internal/core/service/test/unit/school.go
  internal/core/service/test/unit/school_test.go
  internal/core/service/test/unit/stat_test.go
  internal/core/service/test/unit/user.go
  internal/core/service/test/unit/user_test.go
  internal/core/service/user.go
Labels: backend

#20 backend db migrations
  Makefile
  README.md
  docker-compose.yml
  docs/images/scheme.png
  generator.py
  migrations/1_initialize_schema.down.sql
  migrations/1_initialize_schema.up.sql
  migrations/2_insert_data.down.sql
  migrations/2_insert_data.up.sql
  migrations/3_insert_bulk_data.down.sql
  migrations/3_insert_bulk_data.up.sql
Labels: backend

#21 backend repository
  Makefile
  go.mod
  go.sum
  internal/adapter/repository/postgres/course.go
  internal/adapter/repository/postgres/entity/course.go
  internal/adapter/repository/postgres/entity/lesson.go
  internal/adapter/repository/postgres/entity/review.go
  internal/adapter/repository/postgres/entity/school.go
  internal/adapter/repository/postgres/entity/stat.go
  internal/adapter/repository/postgres/entity/user.go
  internal/adapter/repository/postgres/entity/util.go
  internal/adapter/repository/postgres/errors.go
  internal/adapter/repository/postgres/lesson.go
  internal/adapter/repository/postgres/review.go
  internal/adapter/repository/postgres/school.go
  internal/adapter/repository/postgres/stat.go
  internal/adapter/repository/postgres/test/course.go
  internal/adapter/repository/postgres/test/course_test.go
  internal/adapter/repository/postgres/test/lesson.go
  internal/adapter/repository/postgres/test/lesson_test.go
  internal/adapter/repository/postgres/test/review.go
  internal/adapter/repository/postgres/test/review_test.go
  internal/adapter/repository/postgres/test/school.go
  internal/adapter/repository/postgres/test/school_test.go
  internal/adapter/repository/postgres/test/stat.go
  internal/adapter/repository/postgres/test/stat_test.go
  internal/adapter/repository/postgres/test/user.go
  internal/adapter/repository/postgres/test/user_test.go
  internal/adapter/repository/postgres/test/util.go
  internal/adapter/repository/postgres/user.go
  internal/adapter/storage/minio/minio.go
  internal/adapter/storage/minio/test/files/test.jpeg
  internal/adapter/storage/minio/test/files/test.md
  internal/adapter/storage/minio/test/files/test.png
  internal/adapter/storage/minio/test/storage_test.go
  internal/adapter/storage/minio/test/util.go
  internal/core/service/test/integration/lesson_test.go
  internal/core/service/test/integration/migrations/1_initialize_schema.up.sql
  internal/core/service/test/integration/migrations/2_insert_data.up.sql
  internal/core/service/test/integration/review_test.go
  internal/core/service/test/integration/school_test.go
  internal/core/service/test/integration/user_test.go
  internal/core/service/test/integration/util.go
Labels: backend

#22 backend: add openapi documentation
  docs/docs.go
  docs/openapi3.yaml
  docs/swagger.json
  docs/swagger.yaml
Labels: backend

#23 backend: http
  internal/adapter/delivery/http/v1/auth.go
  internal/adapter/delivery/http/v1/course.go
  internal/adapter/delivery/http/v1/dto/auth.go
  internal/adapter/delivery/http/v1/dto/course.go
  internal/adapter/delivery/http/v1/dto/lesson.go
  internal/adapter/delivery/http/v1/dto/review.go
  internal/adapter/delivery/http/v1/dto/school.go
  internal/adapter/delivery/http/v1/dto/stat.go
  internal/adapter/delivery/http/v1/dto/user.go
  internal/adapter/delivery/http/v1/handler.go
  internal/adapter/delivery/http/v1/media.go
  internal/adapter/delivery/http/v1/payment.go
  internal/adapter/delivery/http/v1/response.go
  internal/adapter/delivery/http/v1/school.go
  internal/adapter/delivery/http/v1/user.go
Labels: backend

#24 backend: adapters
  go.mod
  go.sum
  internal/adapter/auth/adapter/storage/redis/redis.go
  internal/adapter/auth/jwt/jwt.go
  internal/adapter/auth/port/storage.go
  internal/adapter/payment/yoomoney/yoomoney.go
  pkg/database/postgres/postgres.go
  pkg/database/redis/redis.go
  pkg/minio/minio.go
Labels: backend

#26 frontend: api
  frontend/.eslintignore
  frontend/.eslintrc.cjs
  frontend/.github/workflows/default.yml
  frontend/.gitignore
  frontend/.npmrc
  frontend/.prettierignore
  frontend/.prettierrc
  frontend/.vscode/settings.json
  frontend/Dockerfile
  frontend/README.md
  frontend/docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.cjs
  frontend/src/app.d.ts
  frontend/src/app.html
  frontend/src/app.postcss
  frontend/src/hooks.server.ts
  frontend/src/lib/api/api.ts
  frontend/static/favicon.png
  frontend/static/fonts/AbrilFatface.ttf
  frontend/svelte.config.js
  frontend/tailwind.config.ts
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: frontend

#28 add docs
  internal/core/domain/auth.go
  internal/core/domain/course.go
  internal/core/domain/file.go
  internal/core/domain/id.go
  internal/core/domain/lesson.go
  internal/core/domain/payment.go
  internal/core/domain/review.go
  internal/core/domain/school.go
  internal/core/domain/stat.go
  internal/core/domain/user.go
  internal/core/errs/errors.go
  internal/core/port/auth.go
  internal/core/port/course.go
  internal/core/port/lesson.go
  internal/core/port/payment.go
  internal/core/port/repository.go
  internal/core/port/review.go
  internal/core/port/school.go
  internal/core/port/service.go
  internal/core/port/stat.go
  internal/core/port/storage.go
  internal/core/port/user.go
Labels: documentation
